### ISSUE TITLE
Adding opening and closing slide

### ISSUE THREAD

**Issue by driesnuttin25** [Benemenn/HackOurCoffeemaker#1]
Could it be interesting to include an opening/introduction slide to the powerpoint, and an ending slide?
I'm not entirely sure how "professional" this has to be. We could always utilise chatgpt for any cool images if we'd like to set ourselves apart from the rest ;)

![image](https://github.com/user-attachments/assets/8a2edf25-3ea0-452d-9795-d9a7cebc44f5)

**Comment by Benemenn** [comment]
yes, great idea :)

**Comment by kjaeg** [comment]
I like that idea too! Just feel free to add an introduction and ending slide!
